name: "validate in docker"
on:
  schedule: [ { cron: "50 21 * * 0" } ] # run every Sunday 21h50
  pull_request:
  push:
    branches: [ stable  ]
jobs:
  build_in_docker:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version:  ['latest', 'oldest']
        compiler: ['gcc', 'clang']
        mpi:      ['openmpi','mpich']
        variant:  ['mini', 'all']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          VERSION: ${{ matrix.version }}
          COMPILER: ${{ matrix.compiler }}
          MPI: ${{ matrix.mpi }}
          VARIANT: ${{ matrix.variant }}
        run: ./tests/test_install_in_docker
