name: "validate in docker"
on:
  pull_request:
  push:
    branches: [ stable  ]
jobs:
  build_in_docker:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version:  ['latest', 'oldest']
        compiler: ['gcc', 'clang']
        mpi:      ['openmpi']
        level:    ['mini', 'all']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          VERSION: ${{ matrix.version }}
          COMPILER: ${{ matrix.compiler }}
          MPI: ${{ matrix.mpi }}
          LEVEL: ${{ matrix.level }}
        run: ./tests/test_install_in_docker
